version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: yana-nginx
    ports:
      - "8088:8088"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.29
    container_name: yana-mysql
    restart: always
    tty: true
    ports:
      - "3406:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yana-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    image: composer:latest
    container_name: yana-composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel
volumes:
  dbdata:
    driver: local